classroom_mqtt/authentication/urls.py
from django.urls import path
from authentication import views

app_name = 'authentication'

urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout'),
    path('show_messages/<str:tname>/', views.show_messages, name='show_messages'),
    path('register_student/', views.register_student, name='register_student'),
    path('register_teacher/', views.register_teacher, name='register_teacher'),
    path('home/', views.home_page, name='publish_message'),
    path('publish_message/<int:t_id>/', views.publish_message, name='message_content'),
    path('publish_encrypt_key/', views.publish_encrypt_key, name='publish_encrypt_key'),
    path('publish_encrypt_message/<str:key>/', views.publish_encrypted_message, name='publish_encrypt_message'),
    path('receive_file/', views.receive_file, name='receive_file'),
    path('start_send_msg_enc/', views.start_key_message, name='start_key_msg'),
    path('receive_key/', views.receive_key, name='receive_key'),
    path('send_file/', views.send_file, name='send_file'),
    path('start_send_file/', views.start_file_send, name='send_actual_file'),
    path('snd_file/<str:fname>/', views.snd_file, name='snd_file'),
    path('publish_options/<int:t_id>/', views.publish_options, name='publish_options'),
    path('subscribe_options/', views.subscribe_options, name='subscribe_options'),
    path('subscribe_file/', views.subscribe_file, name='subscribe_file'),
    path('subscribe/<int:t_id>/', views.subs, name='subscribe'),
    path('new_topic/', views.tpc, name='create_topic'),
]

classroom_mqtt/classroom_mqtt/urls.py
from django.contrib import admin
from django.urls import path, include
from authentication import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.register_all, name='register_all'),
    path('auth/', include('authentication.urls')),

]

classroom_mqtt/authentication/models.py
from django.contrib.auth.models import User
from django.db import models


class Usertype(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Topic(models.Model):
    topic = models.CharField(max_length=100)

    def __str__(self):
        return self.topic


class Messages(models.Model):
    topic = models.CharField(max_length=100)
    message = models.CharField(max_length=100)

    def __str__(self):
        return self.topic


class SentFiles(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class SentKey(models.Model):
    key = models.CharField(max_length=100)

    def __str__(self):
        return self.key

classroom_mqtt/authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from authentication.models import Topic,SentFiles


class CreateTopic(forms.ModelForm):
    class Meta:
        model = Topic
        fields = '__all__'


class Registration(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError('Password mismatch')
        return confirm_password


class PublishMessage(forms.Form):
    message = forms.CharField(max_length=100)


class PublishFile(forms.ModelForm):

    class Meta:
        model = SentFiles
        fields = '__all__'

classroom_mqtt/authentication/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
import time
import hashlib
from cryptography.fernet import Fernet
from django.urls import reverse
import publish
import paho.mqtt.client as paho
from authentication.forms import Registration, PublishMessage, PublishFile, CreateTopic
from authentication.models import Topic, Usertype, Messages, SentFiles, SentKey


def register_all(request):
    return render(request, 'authentication/register_all.html')


def home_page(request):
    all_topics = Topic.objects.all()
    return render(request, 'authentication/home_page.html', {'topics': all_topics})


def login_user(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            u = User.objects.get(username=user)
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            if 'next' in request.GET:
                return redirect(request.GET.get('next'))
            if u.usertype.is_teacher:
                return redirect('authentication:publish_message')
            elif u.usertype.is_student:
                return redirect('authentication:publish_message')

            else:
                return HttpResponse('User does not exist')

    return render(request, 'authentication/login.html', {'form': form})


@login_required
def logout_user(request):
    logout(request)


def register_student(request):
    form = Registration()
    if request.method == 'POST':
        form = Registration(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()

            ut = Usertype.objects.create(user=user, is_student=True)
            ut.save()

            return redirect('authentication:login_user')

    return render(request, 'authentication/register.html', {'form': form})


def register_teacher(request):
    form = Registration()
    if request.method == 'POST':
        form = Registration(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()

            ut = Usertype.objects.create(user=user, is_teacher=True)
            ut.save()

            return redirect('authentication:login_user')

    return render(request, 'authentication/register.html', {'form': form})


def subscribe_options(request):
    return render(request, 'authentication/subscribe_options.html')


def publish_options(request, t_id=None):
    return render(request, 'authentication/publish_options.html', {'t_id': t_id})


def publish_encrypted_message(request, key):
    cipher = Fernet(key)
    client = paho.Client(client_id="1234", clean_session=False, userdata=None, protocol=paho.MQTTv311, )
    broker = "broker.mqttdashboard.com"
    message = b'This is an encrypted message'

    encrypted_message = cipher.encrypt(message)
    out_message = encrypted_message.decode()  # turn it into a string to send

    print("connecting to broker ", broker)
    client.connect(broker)
    client.loop_start()
    print("publishing encrypted message ", encrypted_message)

    client.publish("trial/encrypted_message", out_message, qos=1, retain=True)
    time.sleep(4)
    client.disconnect()
    client.loop_stop()


def receive_key(request):
    hostname = 'broker.mqttdashboard.com'
    client = paho.Client(client_id="1235", clean_session=False, userdata=None, protocol=paho.MQTTv311)
    client.on_subscribe = on_subscribe
    client.on_message = on_message
    client.on_connect = on_connect
    client.connect(hostname, 1883)
    client.subscribe("trial/encrypt", qos=1)
    client.loop_forever()


def publish_encrypt_key(request):
    cipher_key = Fernet.generate_key()
    cipher = Fernet(cipher_key)
    print(cipher_key)
    print(type(cipher))
    k = SentKey.objects.create(key=cipher_key)
    k.save()

    def on_publish(client, userdata, mid):
        print("mid: " + str(mid))

    hostname = 'broker.mqttdashboard.com'
    broker = "broker.mqttdashboard.com"

    client = paho.Client(client_id="1234", clean_session=False, userdata=None, protocol=paho.MQTTv311, )
    client.on_publish = on_publish
    client.will_set("trial/topic2", payload="bye!", qos=1, retain=False)
    client.username_pw_set("shankar", "shankar001")
    client.connect_async(hostname, 1883)
    client.loop_start()
    i = 0
    while i < 1:
        message = cipher_key
        (rc, mid) = client.publish("trial/key", message, qos=1, retain=True)
        time.sleep(2)
        i = i + 1

    client.disconnect()
    return HttpResponse('Key is sent')


def publish_message(request, t_id=None):
    form = PublishMessage()
    count = 1
    if request.method == 'POST':
        form = PublishMessage(request.POST)
        if form.is_valid():
            print('Form is valid')
            topic = Topic.objects.get(pk=t_id)
            message = form.cleaned_data['message']
            while count < 100:
                publish.publish_message(message, topic)
                count += 1
        else:
            print('Form is invalid')

    return render(request, 'authentication/publish_message.html', {'form': form})


bytes_in = 0
bytes_out = 0


def rcv_file(fname):
    broker = "broker.mqttdashboard.com"
    topic = "data/file_send"
    qos = 1
    data_block_size = 2000
    filename = fname
    file_out = "copy-" + filename
    fout = open(file_out, "wb")

    def process_message(msg):
        """ This is the main receiver code
           """
        print("received ")
        global bytes_in
        if len(msg) == 200:  # is header or end
            print("found header")
            msg_in = msg.decode("utf-8")
            msg_in = msg_in.split(",,")
            print(msg_in)
            if msg_in[0] == "end":  # is it really last packet?
                in_hash_final = in_hash_md5.hexdigest()
                if in_hash_final == msg_in[2]:
                    print("File copied OK -valid hash  ", in_hash_final)
                    return -1
                else:
                    print("Bad file receive   ", in_hash_final)
                return False
            else:
                if msg_in[0] != "header":
                    in_hash_md5.update(msg)
                    return True
                else:
                    return False
        else:
            bytes_in = bytes_in + len(msg)
            in_hash_md5.update(msg)
            print("found data bytes =", bytes_in)
            return True

    # define callback
    def on_message(client, userdata, message):
        # time.sleep(1)
        global run_flag
        # print("received message =",str(message.payload.decode("utf-8")))
        ret = process_message(message.payload)
        if ret:
            fout.write(message.payload)
        if ret == -1:
            run_flag = False  # exit receive loop
            print("complete file received")

    client = paho.Client("client-receive-001")
    client.on_message = on_message
    client.mid_value = None

    print("connecting to broker ", broker)
    client.connect(broker)

    print("subscribing ")
    client.subscribe(topic)
    time.sleep(2)
    start = time.time()
    time_taken = time.time() - start
    in_hash_md5 = hashlib.md5()
    run_flag = True

    while run_flag:
        client.loop(00.1)  # manual loop
        pass
    client.disconnect()
    client.loop_stop()
    fout.close()


def snd_file(request, fname):
    global bytes_out
    broker = "broker.mqttdashboard.com"
    topic = "data/file_send"
    qos = 1
    filename = fname

    file = filename.split('.')
    data_block_size = 2000
    fo = open(filename, "rb")
    file_out = "copy-" + filename
    fout = open(file_out, "wb")

    def on_publish(client, userdata, mid):
        # logging.debug("pub ack "+ str(mid))
        client.mid_value = mid
        client.puback_flag = True

    # waitfor loop
    def wait_for(client, msgType, period=0.25, wait_time=40, running_loop=False):
        client.running_loop = running_loop  # if using external loop
        wcount = 0
        # return True
        while True:
            # print("waiting"+ msgType)
            if msgType == "PUBACK":
                if client.on_publish:
                    if client.puback_flag:
                        return True

            if not client.running_loop:
                client.loop(.01)  # check for messages manually
            time.sleep(period)
            # print("loop flag ",client.running_loop)
            wcount += 1
            if wcount > wait_time:
                print("return from wait loop taken too long")
                return False
        return True

    def c_publish(client, topic, out_message, qos):
        res, mid = client.publish(topic, out_message, qos)  # publish
        # return

        if res == 0:  # published ok
            if wait_for(client, "PUBACK", running_loop=True):
                if mid == client.mid_value:
                    print("match mid ", str(mid))
                    client.puback_flag = False  # reset flag
                else:
                    print("quitting")
                    raise SystemExit("not got correct puback mid so quitting")

            else:
                raise SystemExit("not got puback so quitting")

    def send_header(filename):
        header = "header" + ",," + filename + ",,"
        header = bytearray(header, "utf-8")
        header.extend(b',' * (200 - len(header)))
        print(header)
        c_publish(client, topic, header, qos)

    def send_end(filename):

classroom_mqtt/authentication/templates/authentication/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />

    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication/base.css' %}" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Oswald:300,400,500|Roboto+Condensed:300i,400"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous"
    />

    {% block css %} {% endblock %}
  </head>

  {% block html %} {% endblock %}
</html>

classroom_mqtt/authentication/templates/authentication/create_topic.html
{% extends 'authentication/base.html' %} {% block css %}
<title>home</title>
{% load static %}
<link rel="stylesheet" href="{% static 'authentication/home_page.css' %}" />
{% endblock %} {% block html %}
<body>
  <nav
    class="navbar navbar-expand-lg navbar-light bg-light justify-content-between"
  >
    <a class="navbar-brand" href="http://127.0.0.1:8000/auth/home/">
      {% load static %}
      <img
        src="{% static 'authentication/images/nav_logo.png' %}"
        width="180"
      />
    </a>
    <div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'authentication:create_topic' %}">
            <i class="fas fa-plus-circle"></i>
            Create Topic
          </a>
        </li>
      </ul>
    </div>
  </nav>
  <br />
  <br />

  <div class="container">
    <div class="card card-body">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create Topic" class="btn btn-primary " />
      </form>
    </div>
  </div>

  <script>
    document.getElementById("id_topic").classList.add("form-control");
  </script>
</body>
{% endblock %}

classroom_mqtt/authentication/templates/authentication/home_page.html
{% extends 'authentication/base.html' %} {% block css %}
<title>home</title>
{% load static %}
<link rel="stylesheet" href="{% static 'authentication/home_page.css' %}" />
{% endblock %} {% block html %}

<body>
  <nav
    class="navbar navbar-expand-lg navbar-light bg-light justify-content-between"
  >
    <a class="navbar-brand" href="{% url 'register_all' %}">
      {% load static %}
      <img
        src="{% static 'authentication/images/nav_logo.png' %}"
        width="180"
      />
    </a>
    <div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'authentication:create_topic' %}">
            <i class="fas fa-plus-circle"></i>
            Create Topic
          </a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    <br /><br />
    <div class="row">
      <div class="col" style="text-align: center">
        <a
          href="{% url 'authentication:subscribe_file' %}"
          class="btn btn-outline-info btn-block"
        >
          <i class="fa fa-plus"></i>
          &nbsp;&nbsp;Subscribe to a file </a
        ><br /><br />
      </div>

        <div class="col" style="text-align: center">
        <a
          href="{% url 'authentication:send_actual_file' %}"
          class="btn btn-outline-info btn-block"
        >
          <i class="fa fa-plus"></i>
          &nbsp;&nbsp;Send a file </a
        ><br /><br />
      </div>

{#        <div class="col" style="text-align: center">#}
{#        <a#}
{#          href="{% url 'authentication:publish_encrypt_key' %}"#}
{#          class="btn btn-outline-info btn-block"#}
{#        >#}
{#          <i class="fa fa-plus"></i>#}
{#          &nbsp;&nbsp;Send the key </a#}
{#        ><br /><br />#}
{#      </div>#}

{#        <div class="col" style="text-align: center">#}
{#        <a#}
{#          href="{% url 'authentication:receive_key' %}"#}
{#          class="btn btn-outline-info btn-block"#}
{#        >#}
{#          <i class="fa fa-plus"></i>#}
{#          &nbsp;&nbsp;Receive the key </a#}
{#        ><br /><br />#}
{#      </div>#}

{#        <div class="col" style="text-align: center">#}
{#        <a#}
{#          href="{% url 'authentication:start_key_msg' %}"#}
{#          class="btn btn-outline-info btn-block"#}
{#        >#}
{#          <i class="fa fa-plus"></i>#}
{#          &nbsp;&nbsp;Send encrypted message </a#}
{#        ><br /><br />#}
{#      </div>#}

        <div class="col" style="text-align: center">
        <a
          href="{% url 'authentication:send_file' %}"
          class="btn btn-outline-info btn-block"
        >
          <i class="fa fa-plus"></i>
          &nbsp;&nbsp;Publish filename</a
        ><br /><br />
      </div>

      <div class="col" style="text-align: center">
        <a
          href="{% url 'authentication:receive_file' %}"
          class="btn btn-outline-info btn-block"
        >
          <i class="fa fa-arrow-circle-down "></i>
          &nbsp;&nbsp;Receive File </a
        ><br /><br />
      </div>
    </div>
    <br />
    {% for topic in topics %}
    <div class="row" style="padding-left: 8%; padding-right: 8%;">
      <div class="col-3">{{ topic }}</div>
      <div class="col-3">
        <a
          class="btn btn-block btn-outline-warning"
          href="{% url 'authentication:show_messages' topic %}"
        >
          <i class="fa fa-comments"></i>
          &nbsp;&nbsp;Messages</a
        >
      </div>
      <div class="col-3">
        <a
          class="btn btn-block btn-outline-primary"
          href="{% url 'authentication:publish_options' topic.id %}"
          ><i class="fa fa-arrow-circle-up"></i>&nbsp;&nbsp;Publish</a
        >
      </div>
      <div class="col-3">
        <a
          class="btn btn-block btn-outline-danger"
          href="{% url 'authentication:subscribe' topic.id %}"
          >Subscribe to a message</a
        >
      </div>
    </div>
    <br />
    <hr />

    {% endfor %}
  </div>
</body>
{% endblock %}

classroom_mqtt/authentication/templates/authentication/login.html
{% extends 'authentication/base.html' %} {% block css %}
<title>Register</title>
{% load static %}
<link rel="stylesheet" href="{% static 'authentication/register_all.css' %}" />
{% endblock %} {% block html %}

<body style="background: none;">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'register_all' %}">Back</a>
  </nav>
  <br /><br />
  <div class="container">
    <div class="row">
      <div class="col-4">
        <form method="post">
          {% csrf_token %} {% if form.errors %}
          <h6 style="text-align:center; color:red">
            Your username and password didn't match
          </h6>
          <br /><br />
          {% endif %} {% for field in form %}
          <div class="wrap-input100 validate-input form-group">
            <span class="label-input100 p-t-30">{{ field.label_tag }}</span
            ><br />
            {{ field }}
            <span class="focus-input100"></span>
          </div>
          {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
          {% endfor %} {% endfor %}
          <br />
          <input
            type="submit"
            value="Login"
            class="btn btn-block btn-outline-primary"
          />
        </form>
      </div>
      <div class="col-8" style="padding-left:25%;">
        {% load static %}
        <img src="{%static 'authentication/images/bg_2.png' %}" width="420" />
      </div>
    </div>
  </div>
  <script>
    document.getElementById("id_username").classList.add("form-control");
    document.getElementById("id_password").classList.add("form-control");
  </script>
</body>
{% endblock %}

classroom_mqtt/authentication/templates/authentication/publish_options.html
{% extends "authentication/base.html" %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    {% block css %}
    <title>Publish</title>
    {% endblock %}
  </head>
  {% block html %}
  <body>
    <nav
      class="navbar navbar-expand-lg navbar-light bg-light justify-content-between"
    >
      <a class="navbar-brand" href="http://127.0.0.1:8000/auth/home/">
        {% load static %}
        <img
          src="{% static 'authentication/images/nav_logo.png' %}"
          width="180"
        />
      </a>
    </nav>
    <br />
    <br />
    <div class="container">
      <div class="row">
        <div
          class="col"
          style="text-align: center; border-right: 2px solid #0069d9"
        >
          <a
            href="{% url 'authentication:message_content' t_id %}"
            class="btn btn-primary btn-lg"
          >
            <i class="fa fa-cloud-upload-alt "></i>&nbsp;&nbsp;Publish Message
          </a>
          <br /><br />
        </div>
{#        <div class="col" style="text-align: center;">#}
{#          <a#}
{#            href="{% url 'authentication:send_file' %}"#}
{#            class="btn btn-primary btn-lg"#}
{#          >#}
{#            <i class="fa fa-file-upload"></i>&nbsp;&nbsp;Send a File#}
{#          </a>#}
{#          <br /><br />#}
{#        </div>#}
      </div>
    </div>
  </body>
  {% endblock %}
</html>

classroom_mqtt/authentication/templates/authentication/register_all.html
{% extends 'authentication/base.html' %}

{% block css %}
<title>Welcome</title>
{% load static %}
<link rel="stylesheet" href="{% static 'authentication/register_all.css' %}" />
{% endblock %}

{% block html %}

<body class="bg">
  <div class="container-fluid">
    <div class="fc">
      <center style="font-size: 30px;color: #d9534f">First time?</center>
      <a href="{% url 'authentication:register_student' %}" class="d-inline-block m-3">
        <button type="button" class="btn btn-outline-danger d-inline-block">
          Student Registration
        </button>
      </a>
      <a href="{% url 'authentication:register_teacher' %}" class="d-inline-block m-3">
        <button type="button" class="btn btn-outline-danger d-inline-block">
          Teacher Registration
        </button>
      </a>
    </div>
    <div class="sc justify-content-center" style="text-align: center">
      <div style="font-size: 30px;color: #428bca ;display: inline-block">Already a member?
      </div>
      <br />
      <a href="{% url 'authentication:login_user' %}" class="d-inline-block m-3" style="display: inline-block">
        <button type="button" class="btn btn-outline-primary d-inline-block">
          User login
        </button>
      </a>
    </div>
  </div>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossOrigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossOrigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossOrigin="anonymous"></script>
</body>
{% endblock %}

classroom_mqtt/authentication/templates/authentication/register_student.html
{% extends 'authentication/base.html' %} {% block css %}
<title>Register_Student</title>
{% load static %}
<link
  rel="stylesheet"
  href="{% static 'authentication/register_student.css' %}"
/>
{% endblock %} {% block html %}

<body>
  <div class="container">
    <form method="post">
      {% csrf_token %} {% for field in form %}
      <div class="wrap-input100 validate-input form-group">
        <span class="label-input100 p-t-30">{{ field.label_tag }}</span
        ><br />
        {{ field | add_class: "input100 form-control" }}
        <span class="focus-input100"></span>
      </div>
      {% for error in field.errors %}
      <p style="color: red">{{ error }}</p>
      {% endfor %} {% endfor %}
      <a
        href="{% url 'authentication:register_student' %}"
        class="dis-block txt3 hov1 p-r-30 p-t-10 p-b-10 p-l-30"
      >
        Register as a student
        <i class="fa fa-long-arrow-right m-l-5"></i>
      </a>
    </form>
  </div>
  <script>
    document.getElementById("id_username").classList.add("form-control");
    document.getElementById("id_email").classList.add("form-control");
  </script>
</body>

{% endblock %}

classroom_mqtt/authentication/templates/authentication/show_messages.html
{% extends 'authentication/base.html' %} {% block css %}{% load widget_tweaks %}
<title>home</title>
{% load static %}
<link rel="stylesheet" href="{% static 'authentication/home_page.css' %}" />
{% endblock %} {% block html %}
<body>
  <nav
    class="navbar navbar-expand-lg navbar-light bg-light justify-content-between"
  >
    <a class="navbar-brand" href="http://127.0.0.1:8000/auth/home/">
      {% load static %}
      <img
        src="{% static 'authentication/images/nav_logo.png' %}"
        width="180"
      />
    </a>
    <div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'authentication:create_topic' %}">
            <i class="fas fa-plus-circle"></i>
            Create Topic
          </a>
        </li>
      </ul>
    </div>
  </nav>
  <br />
  <br />
  <div class="container">
    <div class="card">
      <div class="card-header">
        <h2>All Messages</h2>
      </div>
      <div class="card-body">
        <div class="list-group">
          {% for message in messages %}
          <div class="list-group-item">
            {{ message.message }}
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock %}

classroom_mqtt/authentication/templates/authentication/subscribe.html
{% extends 'authentication/base.html' %} {% block css %}
<title>home</title>
{% load static %}
<link rel="stylesheet" href="{% static 'authentication/home_page.css' %}" />
{% endblock %} {% block html %}

<body>
  <nav
    class="navbar navbar-expand-lg navbar-light bg-light justify-content-between"
  >
    <a class="navbar-brand" href="http://127.0.0.1:8000/auth/home/">
      {% load static %}
      <img
        src="{% static 'authentication/images/nav_logo.png' %}"
        width="180"
      />
    </a>
  </nav>

  <div class="conatiner" style="padding:5%;">
    <div class="row">
      <!-- code for recieving messages from topic -->
    </div>
  </div>
</body>

{% endblock %}

classroom_mqtt/authentication/templates/authentication/subscribe_options.html
{% extends "authentication/base.html" %} {% block css %}
<title>Subscribe</title>
{% endblock %} {% block html %}
<body>
  <nav
    class="navbar navbar-expand-lg navbar-light bg-light justify-content-between"
  >
    <a class="navbar-brand" href="http://127.0.0.1:8000/auth/home/">
      {% load static %}
      <img
        src="{% static 'authentication/images/nav_logo.png' %}"
        width="180"
      />
    </a>
  </nav>
  <div class="container row">
    <div class="col">
      <a href="{% url 'authentication:subscribe' %}"
        ><button class="btn btn-outline-primary">
          Subscribe to a message
        </button></a
      ><br /><br />
    </div>
  </div>
</body>
{% endblock %}